### ISSUE TITLE
[FEAT] Automated payback

### ISSUE THREAD

**Issue by MathisLec** [MathisLec/Git-Project#13]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I must go on your another website to get payback.

**Describe the solution you'd like**
I wanted you to implement a system to get the payback directly from your first website.

**Comment by RandjithC** [comment]
Hello,
The feature about the payback has been added on the website.

![image](https://github.com/MathisLec/Git-Project/assets/116685493/f7734b2f-8520-4acf-9c6f-87033614cc40)

You will receive an email to update the browser and get this feature on your browser for the website

The email should have this logo on the contents

![image](https://github.com/MathisLec/Git-Project/assets/116685493/3d7221df-ee6c-447f-82fb-07dbdbff1180)

Best regards.
